Assignment4_DIS/Models/ErrorViewModel.cs
using System;

namespace Assignment4_DIS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment4_DIS/Models/Reviews.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment4_DIS.Models
{
    public class ReviewRecord
    {
        [Key]
        public int Id { get; set; }
        public string FuelStation_Name { get; set; }

        public string FuelSTation_Address { get; set; }
        public string CustomerName { get; set; }
        public string Customer_Email { get; set; }
        public string Review { get; set; }

    }

    public class Reviews
    {
        public List<ReviewRecord> reviewRecords{ get; set; }
    }

}

Assignment4_DIS/Models/Station.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment4_DIS.Models
{
     public class Station
{
    [Key]
    public string station_name { get; set; }
    public string Location { get; set; }
    public string fuel_type_code { get; set; }
    public float distance { get; set; }
    public string access_days_time { get; set; }
    public string street_address { get; set; }
    public string city { get; set; }
    public int zip { get; set; }
    public string state { get; set; }
    public string country { get; set; }
    public string ev_pricing { get; set; }
    public string ev_network { get; set; }
    
}

public class Stations
{
   
    public List<Station> data { get; set; }

}
}

Assignment4_DIS/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment4_DIS.Models;

namespace Assignment4_DIS.Controllers
{
    public class AboutUsController : Controller
    {   
        public IActionResult AboutUs()
        {
            return View();
        }

       
    }
}

Assignment4_DIS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Assignment4_DIS.Models;

namespace Assignment4_DIS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Assignment4_DIS/Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment4_DIS.Models;

namespace Assignment4_DIS.Controllers
{
    public class MapsController : Controller
    {   
        public IActionResult Maps()
        {
            return View();
        }

       
    }
}

Assignment4_DIS/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment4_DIS.Models;
using Assignment4_DIS.DataAccess;
using Microsoft.EntityFrameworkCore;

namespace Assignment4_DIS.Controllers
{
    public class ReviewsController : Controller
    {[HttpGet]
        public IActionResult Reviews()
        {
            var optionsBuilder = new DbContextOptionsBuilder();
            
            optionsBuilder.UseSqlServer(ApplicationDbContext.GetConnectionString());
            using (var dbContext = new ApplicationDbContext(optionsBuilder.Options))
            {
                var reviewrecords = dbContext.Reviews.ToList();
                var reviews = new Reviews();
                reviews.reviewRecords = reviewrecords;
                return View(reviews);
            }
        }

        [HttpPost]
        public IActionResult DeleteReview(int id)
        {
            var optionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseSqlServer(ApplicationDbContext.GetConnectionString());
            using (var dbContext = new ApplicationDbContext(optionsBuilder.Options))
            {
                var review = new ReviewRecord() { Id = id };
                dbContext.Reviews.Remove(review);
                dbContext.SaveChanges();
            }
            return RedirectToAction("Reviews");
        }

        [HttpPost]
        public IActionResult AddReview(string name, string address, string customerName, string email, string Review)
        {
            var optionsBuilder = new DbContextOptionsBuilder();
            optionsBuilder.UseSqlServer(ApplicationDbContext.GetConnectionString());
            using (var dbContext = new ApplicationDbContext(optionsBuilder.Options))
            {
                var review = new ReviewRecord();
                review.FuelStation_Name = name;
                review.FuelSTation_Address = address;
                review.CustomerName = customerName;
                review.Customer_Email = email;
                review.Review = Review;
                //Adding to DB
                dbContext.Reviews.Add(review);
                dbContext.SaveChanges();
            }
            return RedirectToAction("Reviews");
        }

       
    }
}

Assignment4_DIS/Controllers/StationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment4_DIS.Models;
using Assignment4_DIS;
using Assignment4_DIS.DataAccess;
using Assignment4_DIS.APIHandlerManager;
using Newtonsoft.Json;
using System.Net.Http;

namespace Assignment4_DIS.Controllers
{
    public class StationsController : Controller
    {
        static string BASE_URL = "https://developer.nrel.gov/api/alt-fuel-stations/v1/nearest.json?";
        static string API_KEY = "&api_key=h3nD00CFqjd6UuNPe3bZj4iStQ2ZEF6WQvbnSwEL";

        HttpClient httpClient;
        Stations publicStations;

        private readonly APIHandler apiHandler = new APIHandler();

        public StationsController( )
        {
            httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new
            System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        [HttpGet]
        public IActionResult Stations()
        {
            var stations = apiHandler.GetStations();
            ViewBag.location = "tampa";
            return View(stations);
        }

        [HttpPost]
        public IActionResult GetStationsWithLocation(string location)
        {
            
            string extension = "&location="+location+"&status=E&access=public&_fields=fuel_stations.station_name";
            var stations = apiHandler.GetStationWithLocation(extension);
            ViewBag.location = location;
            return View("Stations",stations);
        }

        public IActionResult Charts()
        {
            var stations = apiHandler.GetStations();
            return View(stations);
        }
        public IActionResult Details(string data)
        {
            int rowNumber = int.Parse(data.Split("+")[0]);
            string location = data.Split("+")[1];
            string extension = "&location=" + location + "&status=E&access=public&_fields=fuel_stations.station_name";
            var stations = apiHandler.GetStationWithLocation(extension);
            return View(stations.data[rowNumber]);
        }
    }

}

Assignment4_DIS/Views/AboutUs/AboutUs.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>About Us</title>

    <!--<link rel="stylesheet" type="text/css" href="~/css/Index.css">-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
          rel="stylesheet"
          type="text/css"/>
    <link href="~/css/AboutUs.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
</head>

<body>
    <div class="container">


      <!----  <div class="navbar"> >

            <div id="navbar-links">
                <span> <a href="index.html">Home</a> </span>
            </div>

        </div>--->
        <div class="content">
            <!-- page/table title -->
            <h2 style="text-align: center">Distributed Information Systems - Group 12</h2>
            <!-- one info div per team member -->
            <div class="info-div">
                <img class="intext-image-left" src="~/img/dheeraj.jpg" height="120px" width="120px">
                <p>
                    Dheeraj Yerabati is a graduate student in MS business Analytics and Information Systems with focus on data analytics and Machine Learning looking to tackle real-world challenges. He worked as a Data analyst for Capgemini India for 2 years.
                </p>
            </div>

            <!-- one info div per team member -->
            <div class="info-div">
                <img class="intext-image-left" src="~/img/om.jpg" height="120px" width="120px">
                <p>
                    Omprakash Uppala is pursuing his masters at University of South Florida in Business Analytics and Information Systems. He worked with Wipro technologies back in India.
                </p>
            </div>

            <!-- one info div per team member -->
            <div class="info-div">
                <img class="intext-image-left" src="~/img/raghav.jpeg" height="120px" width="120px">
                <p>
                    Raghavendra is currently pursuing his masters in Business Analytics and information systems at university of south Florida. Prior to his master’s, he had experience in developing supply chain applications for a retail client at Cognizant Technology solutions.
                </p>
            </div>

            <!-- one info div per team member -->
            <div class="info-div">
                <img class="intext-image-left" src="~/img/ER_Diagram.jpg" height="500px" width="600px">
                <p>
                    The database we are using has two tables. Fuel stations table contains the information of all stations within the USA. Review table consist of cutomer details and station details.
                </p>
            </div>

            <div class="info-div about">
                <h3 style="text-align: center">About the Project</h3>
                <p class="p01">
                    The project's goal is to return the closest fuel stations and their information within a certain radius of a given area. Our data comes from Data.gov, a federal government website with data, tools, and services for conducting analysis, developing web and mobile apps, creating data visualizations, and more. We identified
                    the Public API exposed by NREL at the link <a class="link" href="https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/nearest/">Open NREL API</a>.
                    <br>
                    Request URL : GET /api/alt-fuel-stations/v1/nearest.format?parameters  and 
                    Git Hub Link is : <a class="link" href="https://github.com/Omprakashuppala/FuelStations">link</a>
                </p>
            </div>

        </div>


    </div>
</body>

</html>

Assignment4_DIS/Views/Home/Index.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    @*<title>Fuel Station Search</title>*@

    <link rel="stylesheet" type="text/css" href="~/css/Index.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
          rel="stylesheet"
          type="text/css" />
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>

    <div class="content bodybackground">
        <p id="bodyquote">
            Search gas stations in your area and all over the world. The website shows information about the gas station, such as location, phone number, and accessibility, in a list and on a map, and allows you to quickly navigate to the fuel station with just one click. Use this website to find what you're searching for quickly!
        </p>

    </div>
</body>
</html>

Assignment4_DIS/Views/Maps/Maps.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Maps</title>

    <link rel="stylesheet" type="text/css" href="~/css/FuelStations.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
          rel="stylesheet"
          type="text/css" />
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
</head>
<body class="bodybackground">

    <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1cHsbqz9IhM393B_jJ9qEHTt0RqQ_nKeh" width="1500" height="500"></iframe>
</body>
</html>

Assignment4_DIS/Views/Reviews/Reviews.cshtml
@model Assignment4_DIS.Models.Reviews
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    @*<title>Fuel Station Search</title>*@

    <link rel="stylesheet" type="text/css" href="~/css/WriteReviews.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
          rel="stylesheet"
          type="text/css" />
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
</head>
<body>
    <div class="tab" style="text-align:center;">
        <form method="post" asp-controller="Reviews" asp-action="AddReview">

            <div>
                <input class="search1" type="text" placeholder="Write Fuel Station Name" name="name">

                <input class="search2" type="text" placeholder="Write Fuel Station Address" name="address">

                <input class="search1" type="text" placeholder="Write your Name" name="customerName">

                <input class="search2" type="text" placeholder="Write your email id" name="email">

            </div>

            <input class="Review" type="text" placeholder="Write your review here.." name="Review">

            <div>
                <input class="submit" type="submit" value="Submit">

            </div>
        </form>

        <br>
        <table id="t02">

            <tr>
                <th>Fuel Station Name</th>
                <th>Address</th>
                <th>Name</th>
                <th>Email ID</th>
                <th>Review</th>
                <th>Delete Review</th>
            </tr>
           @foreach (var d in Model.reviewRecords)
            {
        <tr>
            <td>@d.FuelStation_Name</td>
            <td>@d.FuelSTation_Address</td>
            <td>@d.CustomerName</td>
            <td>@d.Customer_Email</td>
            <td>@d.Review</td>
            <td>
                @using (Html.BeginForm("DeleteReview", "Reviews", FormMethod.Post))
                {
                    <button value="@d.Id" name="id"  type="submit" class="submit">Delete</button>
                }
             </td>
        </tr>
            }
            </table>
    </div>
</body>
</html>

Assignment4_DIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   
</head>
<body>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="~/css/Index.css">
    <!--<h1>Fuel Station Search web site</h1>-->

    <div class="Navbar" style="background-color: grey !important">
        <div class="Navbarleft">
            <a class="navlinks" asp-action="Index" asp-controller="Home">HOME</a>
            <a class="navlinks" asp-action="Stations" asp-controller="Stations">FUEL STATIONS</a>
            <a Class="navlinks" asp-action="Maps" asp-controller="Maps">MAPS</a>
            <a Class="navlinks" asp-controller="Reviews" asp-action="Reviews">REVIEWS</a>
            <a class="navlinks" asp-controller="AboutUs" asp-action="AboutUs">ABOUT US</a>
            <a class="navlinks" asp-controller="Stations" asp-action="Charts">CHARTS</a>

        </div>
    </div>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
</body>
</html>

Assignment4_DIS/Views/Stations/Charts.cshtml
@model Assignment4_DIS.Models.Stations

@{
    ViewData["Title"] = "Charts";
}

<h1>Showing distance for 5 Gas stations in Tampa</h1>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<div id="chartContainer" class="jumbotron-fluid">
    <script type="text/javascript">

        window.onload = function () {
            var chart = new CanvasJS.Chart("chartContainer", {
                theme: "light2",
                animationEnabled: true,
                title: {
                    text: "Distance of Fuel Stations",
                    padding: 10
                },

                axisX: {
                    title: "Station Name",
                    padding: 10
                },
                axisY: {
                    title: "Distance in Miles",
                    padding: 1
                },
                padding: {
                    left: 0,
                    right: 0,
                    top: 100,
                    bottom: 0
                },

                data: [
                    {
                        type: "bar",
                        dataPoints: [

                            { label: "CHARGER 01", y: @Model.data.ToArray()[0].distance },
                            { label: "BROOKE 02", y: @Model.data.ToArray()[1].distance },
                            { label: "BROOKE 01", y: @Model.data.ToArray()[2].distance },
                            { label: "BROOKE 03", y: @Model.data.ToArray()[3].distance },
                            { label: "SUNTRUST STFC #1", y: @Model.data.ToArray()[4].distance },
                       
                        ]
                    }
                ]
            });
            chart.render();
        };
    </script>
</div>

Assignment4_DIS/Views/Stations/Details.cshtml
@model Assignment4_DIS.Models.Station
    <head>
        <style>
        p {
            width: 100%;
            padding: 15px;
            margin: 5px 0 22px 0;
            display: inline-block;
            border: none;
            background: #f1f1f1;
            color:black;
        }
        </style>
    </head>
<h1>Details of  @Model.station_name</h1>
<body>
    <div class="tab">
        <div>
            <label class="search1"><b>Address</b></label>
            <p class="card-text">@Model.street_address</p>
            <label class="search1"><b>ZipCode</b></label>
            <p class="card-text">@Model.zip</p>
            <label class="search1"><b>Hours of Operation</b></label>
            <p class="card-text">@Model.access_days_time</p>
            <label class="search1"><b>City</b></label>
            <p class="card-text">@Model.city</p>
        </div>
</div>
</body>

Assignment4_DIS/Views/Stations/Stations.cshtml
@model Assignment4_DIS.Models.Stations
@{ int i = -1;}
@{ string location = ViewBag.location;}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>FuelStations</title>

    <link rel="stylesheet" type="text/css" href="../css/FuelStations.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
          rel="stylesheet"
          type="text/css" />
    <link rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css" />
</head>
<body>
        <div class="tab" style="text-align:center;">
            <form method="post" asp-controller="Stations" asp-action="GetStationsWithLocation">

                <input id="txtSearch" class="search" type="text" placeholder="Search here with Location.." name="location">

                <button type="submit">Search</button>

            </form>

            <br>
            <table id="t01">

                <tr>
                    <th>Fuel Station Name</th>
                    <th>Fuel Type</th>
                    <th>Distance In Miles</th>
                    <th>State</th>
                    <th>Country</th>
                    <th>Electric Vehicle Pricing</th>
                    <th>Electric Vehicle Network</th>
                    <th></th>
                    

                </tr>
                @foreach (var d in Model.data)
                {
                  i =i+ 1;

            <tr>
                <td>@d.station_name</td>
                <td>@d.fuel_type_code</td>
                <td>@d.distance</td>
               
               
                
                <td>@d.state</td>
                <td>@d.country</td>
                <td>@d.ev_pricing</td>
                <td>@d.ev_network</td>
                <td>
                    <div class="text-center">
                        <a asp-controller="Stations" asp-action="Details" asp-route-data=@i+@location>Details</a>
                    </div>
                </td>
            </tr>
                   
                }
              
            </table>

        </div>
</body>
</html>